# version: '3.12'

# services:
#   web:
#     build: .
#     ports:
#       - "5000:5000"
#     environment:
#       - DB_USER=${DB_USER}
#       - DB_PASSWORD=${DB_PASSWORD}
#       - DB_HOST=${DB_HOST}
#       - DB_PORT=${DB_PORT}
#       - DB_NAME=${DB_NAME}  
#     depends_on:
#       - db

#   db:
#     image: postgres:13
#     ports:
#       - "5432:5432"
#     environment:
#       - POSTGRES_USER=${POSTGRES_USER}
#       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#       - POSTGRES_DB=${POSTGRES_DB}  
#     volumes:
#       - ./indian_banks.sql:/docker-entrypoint-initdb.d/indian_banks.sql

# volumes:
#   postgres_data:

version: '3.12'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}  

volumes:
  postgres_data:
